### ISSUE TITLE
Redirect loop if installed at domain root

### ISSUE THREAD

**Issue by sumpygump** [volter9/8-cms#1]
I got an Apache internal error when the site was installed at the domain root

`[Sat Oct 17 22:48:44.449136 2015] [core:error] [pid 16447] [client 127.0.0.1:47080] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace., referer: http://8-cms.lvh.me/`

The solution was to add a `RewriteBase /` in the .htaccess file

```
RewriteBase /
RewriteRule (.*) index.php?route=$1 [QSA,L]
```

**Comment by volter9** [comment]
That's strange, I don't have this error. Which version of apache do you have? Just wonder, is there any other workaround to solve this error? I just don't really want to attach RewriteBase.

Can you check the .htaccess configuration with this piece of code before first RewriteCond?:

``` apache
RewriteCond %{ENV:REDIRECT_STATUS} ^$
```

**Comment by sumpygump** [comment]
I am running Apache/2.4.10 (Ubuntu)

Yeah, I agree that requiring a RewriteBase would be annoying.

I think this may be how I have my web server set up in the virtual web config. I have this in my apache conf:

```
    RewriteCond %{HTTP_HOST} ^([^.]+)\.lvh.me$
    RewriteRule ^(.*)$     /var/www/%1/$1 [NC,L]
```

This allows me to go to `http://website.lvh.me` and it will serve up content in `/var/www/website/` for me `lvh.me` and all subdomains point to localhost). It makes it nice to have multiple websites on my dev machine benefiting from being at the base domain root without configuring multiple apache confs for each site or messing with editing the hosts file. I think this is causing the redirect loop if I don't have RewriteBase defined in my site `.htaccess` files.

When I examine the redirect loop, it looks like it is doing this `/about` redirects to `/8-cms/index.php` redirects to `/8-cms/8-cms/index.php` then `/8-cms/8-cms/8-cms/index.php`, etc. I believe this is the interaction between the apache conf and the site .htaccess file. The RewriteBase correctly resolves the issue.

I fiddled with it a bit and can't see another way around it. I guess pay it no mind. Probably not worth sweating about.

**Comment by volter9** [comment]
> Probably not worth sweating about

Maybe not, but in case if somebody will encounter this problem, I can point out this issue, and the problem will be solved (probably) thanks to you and this issue :)

Also, thank you for the trick! :wink: 

I should try this too. The way I'm implementing this is having one virtual host with many subdirectories (I call it php.sandbox). In each directory there's project, I can access it through the `http://php.sandbox/%project_name%`. This is pretty simple to implement, but also forces to think about people who might want to install your CMS/library/PHP code in non DOCUMENT_ROOT directory.
