### ISSUE TITLE
System does not manage content

### ISSUE THREAD

**Issue by jpswade** [volter9/8-cms#2]

**Comment by volter9** [comment]
Then, I have to disappoint you, that any file-flat CMS without an admin panel like Pico isn't a CMS either :)

**Comment by nazar-pc** [comment]
They are not, but that doesn't make this project a CMS either.
This is highly insecure 8 lines of almost useless code:( (which is not true either because 8 lines does nothing and with the rest of files it is more than 8 lines)

**Comment by nitso** [comment]
@nazar-pc bore

**Comment by volter9** [comment]
In case of 8 CMS, CMS stands for «Content Maingate Storage».

**Comment by jpswade** [comment]
It's not a [CMS](https://en.wikipedia.org/wiki/Content_management_system) then, call it something else.

Maybe it's a tiny MVC framework, but it's certainly not a CMS.

**Comment by volter9** [comment]
> tiny MVC framework

That's neither a tiny MVC framework, there's only view part, and controller (maybe), but there's no model,  or model combined with view (return [];).

> It's not a CMS then, call it something else

Why should I call it something else. I'll rename it, but answer me one question:
Why are you caring so much about how I called it? It's just a joke, that's exactly why it's so misleading :smile:
